version: '3.9'


services:

  mqtt:
    container_name: mqtt_broker
    image: emqx/nanomq:0.23

    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883

  gazebo:
    container_name: kapibara_robot_sim
    network_mode: host
    image: robot_gazebo_ros

    privileged: true
    tty: true
    build:
      dockerfile: ./Dockerfile.sim
      context: ./robot
    stop_signal: SIGINT
    stop_grace_period: 30m
    runtime: nvidia
    env_file:
      - ./robot/env/sim
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - ./robot/entrypoint.sh:/entrypoint.sh:rwx
      - ./robot/run_sim.sh:/run_sim.sh:rwx
      - ./robot/commands/:/app/cmd
      - ./robot/dependencies/:/app/dep
      - ./robot/src:/app/src:rw
      - ./robot/dependencies/rosdep_package.list:/etc/ros/rosdep/sources.list.d/20-default.list
      - /sys:/sys
      - /etc/udev:/etc/udev
      - /run/udev:/run/udev
      - /run/dbus/:/run/dbus
      - /dev:/dev

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['1']
            count: all
            capabilities: [gpu]

    devices:
      - "/dev/dri/:/dev/dri/"
      - /dev/snd:/dev/snd
      # - "/dev/kfd:/dev/kfd"

    group_add:
      - video
      - dialout
      - 1001
      # - 993